#!/usr/bin/env ansible-playbook
---
- name: MongoDB

  hosts:
    - vm_tag_debug_db

  become: yes
  become_user: root

  tasks:

    - name: Wait for VMs to start
      wait_for_connection:

    - name: Upgrade system
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
        autoremove: yes
        autoclean: yes
      async: 3600
      poll: 5
      when: upgrade_system | default(false) | bool
      tags:
        - system

    - ansible.builtin.import_role:
        name: googlecloudplatform.google_cloud_ops_agents
      vars:
        agent_type: ops-agent
        main_config_file: ops-agent.config.yml
      tags:
        - google-ops-agent

    - ansible.builtin.import_role:
        name: nodejs

    - name: Check if a reboot is required
      ansible.builtin.shell: "[ -f /var/run/reboot-required ]"
      failed_when: false
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify:
        - reboot
      tags:
        - system

  handlers:

    - name: reboot
      ansible.builtin.reboot:
        msg: Maintenance reboot initiated
