---
- name: Create a partition on secure disk
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present
  when: not ansible_check_mode
  tags:
    - secure-disk

- name: Create a filesystem for the partition
  community.general.filesystem:
    fstype: "{{ secure_disk_fstype }}"
    dev: /dev/sdb1
  when: not ansible_check_mode
  tags:
    - secure-disk

- name: Mount the filesystem
  ansible.posix.mount:
    path: "{{ secure_disk_mount_path }}"
    src: /dev/sdb1
    fstype: "{{ secure_disk_fstype }}"
    state: mounted
  when: not ansible_check_mode
  tags:
    - secure-disk
