---
- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
  tags:
    - mongodb

- name: DEB architecture
  ansible.builtin.shell: dpkg --print-architecture
  register: deb_architecture
  changed_when: false
  tags:
    - mongodb

- name: MongoDB | key
  ansible.builtin.get_url:
    url: "{{ mongodb_key_url }}"
    dest: "{{ mongodb_key_file }}"
  tags:
    - mongodb

- name: MongoDB | apt source
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by={{ mongodb_key_file }}] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    state: present
    filename: "mongodb-org-{{ mongodb_version }}"
  tags:
    - mongodb

- name: MongoDB | install packages
  ansible.builtin.apt:
    update_cache: yes
    name:
      - mongodb-org
      - mongodb-org-server
      - mongodb-org-shell
      - mongodb-org-mongos
      - mongodb-org-tools
      - python3-pymongo
  tags:
    - mongodb

- name: Create /etc/systemd/system/mongod.service.d
  ansible.builtin.file:
    path: /etc/systemd/system/mongod.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - mongodb

- name: Update mongod.service configuration
  ansible.builtin.copy:
    src: systemd-override-mongod.conf
    dest: /etc/systemd/system/mongod.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemctl daemon-reload
    - systemctl restart mongod
  tags:
    - mongodb

- name: Set /etc/logrotate.d/mongod
  ansible.builtin.copy:
    src: logrotate-mongod.conf
    dest: /etc/logrotate.d/mongod
    owner: root
    group: root
    mode: '0644'
  tags:
    - mongodb
    - mongodb-logrotate

- name: "Create {{ mongodb_tls_dir }}"
  ansible.builtin.file:
    path: "{{ mongodb_tls_dir }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0700'
  tags:
    - mongodb
    - mongodb-tls

- name: "Ensure mongodb user has read/execute permissions on {{ mongodb_tls_dir }}/.."
  ansible.posix.acl:
    state: present
    default: yes
    path: "{{ mongodb_tls_dir }}/.."
    etype: user
    entity: mongodb
    permissions: rX
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_ca_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret ca_crt"
  connection: local
  become: no
  run_once: true
  delegate_to: localhost
  register: mongodb_ca_crt
  check_mode: false
  no_log: "{{ not display_diff_secrets }}"
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_ca_crt }}"
  copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_ca_crt }}"
    content: "{{ mongodb_ca_crt.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0600'
  no_log: "{{ not display_diff_secrets }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_crt }}"
  connection: local
  become: no
  run_once: true
  delegate_to: localhost
  register: mongodb_tls_crt
  check_mode: no
  no_log: "{{ not display_diff_secrets }}"
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_crt }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_crt }}"
    content: "{{ mongodb_tls_crt.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0600'
  no_log: "{{ not display_diff_secrets }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_key }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_key }}"
  connection: local
  become: no
  run_once: true
  delegate_to: localhost
  register: mongodb_tls_key
  check_mode: no
  no_log: "{{ not display_diff_secrets }}"
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_key }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_key }}"
    content: "{{ mongodb_tls_key.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0600'
  no_log: "{{ not display_diff_secrets }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_pem }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_pem }}"
  connection: local
  become: no
  run_once: true
  delegate_to: localhost
  register: mongodb_tls_pem
  check_mode: no
  no_log: "{{ not display_diff_secrets }}"
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_pem }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_pem }}"
    content: "{{ mongodb_tls_pem.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0600'
  no_log: "{{ not display_diff_secrets }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve secret {{ mongodb_secret_name_tls_keypassword }}"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_keypassword }}"
  connection: local
  become: no
  run_once: true
  delegate_to: localhost
  register: mongodb_tls_keypassword
  no_log: "{{ not display_diff_secrets }}"
  check_mode: no
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-config

- name: Set /etc/mongod.conf
  ansible.builtin.template:
    src: mongod_replicaset.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify:
    - systemctl restart mongod
  no_log: "{{ not display_diff_secrets }}"
  tags:
    - mongodb
    - mongodb-config

- name: Start and enable service
  ansible.builtin.service:
    name: mongod.service
    state: started
    enabled: yes
  tags:
    - mongodb
