---
- name: "Retrieve secret {{ mongodb_secret_name_tls_key_password }}"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_key_password }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_key_password
  when: mongodb_tls_key_password_enabled | default(false) | bool
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-config

- name: "Retrieve {{ mongodb_secret_name_ca_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_ca_crt }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_ca_crt
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_crt }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_crt
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_key }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_key }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_key
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_pem }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_pem }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_pem
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls
