---
- name: "Create {{ mongodb_tls_dir }}"
  ansible.builtin.file:
    path: "{{ mongodb_tls_dir }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0750'
  tags:
    - mongodb
    - mongodb-tls

- name: "Ensure mongodb user has read/execute permissions on {{ mongodb_tls_dir }}/.."
  ansible.posix.acl:
    state: present
    default: yes
    path: "{{ mongodb_tls_dir }}/.."
    etype: user
    entity: mongodb
    permissions: rX
  tags:
    - mongodb
    - mongodb-tls

- name: "Ensure mongodb group has read/execute permissions on {{ mongodb_tls_dir }}/.."
  ansible.posix.acl:
    state: present
    default: yes
    path: "{{ mongodb_tls_dir }}/.."
    etype: group
    entity: mongodb
    permissions: rX
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_ca_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_ca_crt }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_ca_crt
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_ca_crt }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_ca_crt }}"
    content: "{{ mongodb_ca_crt.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0640'
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_crt }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_crt }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_crt
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_crt }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_crt }}"
    content: "{{ mongodb_tls_crt.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0640'
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_key }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_key }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_key
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_key }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_key }}"
    content: "{{ mongodb_tls_key.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0640'
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Retrieve {{ mongodb_secret_name_tls_pem }} from Secret Manager"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_pem }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_pem
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb
    - mongodb-tls

- name: "Write {{ mongodb_tls_dir }}/{{ mongodb_file_tls_pem }}"
  ansible.builtin.copy:
    dest: "{{ mongodb_tls_dir }}/{{ mongodb_file_tls_pem }}"
    content: "{{ mongodb_tls_pem.stdout }}"
    owner: mongodb
    group: mongodb
    mode: '0640'
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  tags:
    - mongodb
    - mongodb-tls
