---
- name: "Retrieve secret {{ mongodb_secret_name_admin_password }}"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_admin_password }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_admin_password
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb-snapshots

- name: "Retrieve secret {{ mongodb_secret_name_tls_key_password }}"
  ansible.builtin.command: "gcloud secrets versions access latest --secret {{ mongodb_secret_name_tls_key_password }}"
  connection: local
  delegate_to: localhost
  become: no
  run_once: true
  check_mode: false
  changed_when: false
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  register: mongodb_tls_key_password
  environment:
    CLOUDSDK_CORE_PROJECT: "{{ lookup('ansible.builtin.env', 'CLOUDSDK_CORE_PROJECT') }}"
  tags:
    - mongodb-snapshots

- name: Create /etc/google/snapshots
  ansible.builtin.file:
    path: /etc/google/snapshots
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - mongodb-snapshots

- name: Set /etc/google/snapshots/mongo-cmd.sh
  ansible.builtin.template:
    src: mongo-cmd.sh.j2
    dest: /etc/google/snapshots/mongo-cmd.sh
    owner: root
    group: root
    mode: '0600'
  no_log: "{{ not (display_diff_secrets | default(false) | bool) }}"
  tags:
    - mongodb-snapshots

- name: Set /etc/google/snapshots/pre.sh
  ansible.builtin.copy:
    src: snapshot.pre.sh
    dest: /etc/google/snapshots/pre.sh
    owner: root
    group: root
    mode: '0700'
  tags:
    - mongodb-snapshots

- name: Set /etc/google/snapshots/post.sh
  ansible.builtin.copy:
    src: snapshot.post.sh
    dest: /etc/google/snapshots/post.sh
    owner: root
    group: root
    mode: '0700'
  tags:
    - mongodb-snapshots

- name: Ensure /etc/default directory exists
  ansible.builtin.file:
    path: /etc/default
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - mongodb-snapshots

# https://cloud.google.com/compute/docs/disks/creating-linux-application-consistent-pd-snapshots#config
- name: Set /etc/default/instance_configs.cfg
  ansible.builtin.blockinfile:
    path: /etc/default/instance_configs.cfg
    mode: '0644'
    owner: root
    group: root
    create: true
    block: |
      [Snapshots]
      enabled = true
      timeout_in_seconds = 60
  notify:
    - systemctl restart google-guest-agent.service
  tags:
    - mongodb-snapshots
