---
- name: Create a partition on additional disk
  community.general.parted:
    device: /dev/sdb
    number: 1
    state: present
  when: not ansible_check_mode
  tags:
    - extra-disk

- name: Create a filesystem for the partition
  community.general.filesystem:
    fstype: "{{ extra_disk_fstype }}"
    dev: /dev/sdb1
  when: not ansible_check_mode
  tags:
    - extra-disk

- name: Mount the filesystem
  ansible.posix.mount:
    state: mounted
    path: "{{ extra_disk_mount_path }}"
    src: /dev/sdb1
    fstype: "{{ extra_disk_fstype }}"
    opts: discard,defaults
  when: not ansible_check_mode
  tags:
    - extra-disk
